name: CI Artifact Build

on:
  push:
    branches:
      - develop
      - '^release'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:   
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      env:
        REGISTRY: roxsross12
        REPOSITORY: ${{ github.event.repository.name }}
      run: |
        VERSION=`jq -r '.version' ./package.json`
        docker build -t $REGISTRY/$REPOSITORY:$VERSION .
        docker push $REGISTRY/$REPOSITORY:$VERSION
